input {
  tcp {
    host => "0.0.0.0"
    port => 5000
    codec => json_lines
  }
  udp {
    host => "0.0.0.0"
    port => 5000
    codec => json_lines
  }
  beats {
    host => "0.0.0.0"
    port => 5044
  }
}

filter {}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "pre-ticket-%{+YYYY.MM.dd}"
    ecs_compatibility => disabled
  }
}